/**
 * EventSphere Seed Script
 * Run: node seed.js
 * Seeds the database with 24 sample events and an admin user.
 */
require('dotenv').config();
const mongoose = require('mongoose');
const Event = require('./models/Event');
const User = require('./models/User');

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/eventsphere';

const events = [
  {
    title: 'AI & Machine Learning Summit 2025',
    description: 'Join 2,000+ engineers, researchers, and founders at the premier AI conference. Deep dives into LLMs, computer vision, and the future of AI-powered products. Keynotes from Google DeepMind and OpenAI leaders.',
    category: 'tech',
    tags: ['tech', 'ai', 'networking', 'conference', 'analytical'],
    date: new Date('2025-06-15T09:00:00Z'),
    endDate: new Date('2025-06-16T18:00:00Z'),
    location: { city: 'San Francisco', address: 'Moscone Center, 747 Howard St', venue: 'Moscone Center', lat: 37.7845, lng: -122.4009, isOnline: false },
    price: 299,
    image: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800',
    organizer: { name: 'TechConf Global', email: 'hello@techconfglobal.com' },
    capacity: 2000,
    isFeatured: true,
  },
  {
    title: 'Hackathon: Build the Future in 48 Hours',
    description: 'Code, design, and innovate over two intense days with teams from around the world. $50,000 in prizes across 5 categories. Free meals, swag, and mentorship from top engineers.',
    category: 'tech',
    tags: ['tech', 'hackathon', 'coding', 'competitive', 'networking'],
    date: new Date('2025-07-12T08:00:00Z'),
    endDate: new Date('2025-07-13T18:00:00Z'),
    location: { city: 'New York', address: '450 W 33rd St', venue: 'Pier 94', lat: 40.7128, lng: -74.006, isOnline: false },
    price: 0,
    image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800',
    organizer: { name: 'HackNYC', email: 'events@hacknyc.io' },
    capacity: 500,
    isFeatured: true,
  },
  {
    title: 'Coachella Valley Music & Arts Festival',
    description: 'Three weekends of the world\'s best music across 8 stages. Headliners include chart-topping pop, electronic, hip-hop, and indie acts, surrounded by stunning art installations in the desert.',
    category: 'music',
    tags: ['music', 'festival', 'art', 'outdoor', 'social'],
    date: new Date('2025-04-18T12:00:00Z'),
    endDate: new Date('2025-04-20T23:59:00Z'),
    location: { city: 'Indio', address: '81-800 Ave 51', venue: 'Empire Polo Club', lat: 33.6818, lng: -116.2378, isOnline: false },
    price: 549,
    image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
    organizer: { name: 'Goldenvoice', email: 'info@coachella.com' },
    capacity: 125000,
    isFeatured: true,
  },
  {
    title: 'Electronic Dreams: A DJ Night Experience',
    description: 'Six of the world\'s best electronic music DJs take over a 5,000-person warehouse. Cutting-edge laser light shows, spatial audio, and immersive art installations. 18+.',
    category: 'music',
    tags: ['music', 'dance', 'festival', 'energetic', 'social'],
    date: new Date('2025-08-02T20:00:00Z'),
    endDate: new Date('2025-08-03T04:00:00Z'),
    location: { city: 'Los Angeles', address: '1720 E 16th St', venue: 'The Factory', lat: 34.0195, lng: -118.2436, isOnline: false },
    price: 75,
    image: 'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800',
    organizer: { name: 'Neon Collective', email: 'tickets@neoncollective.com' },
    capacity: 5000,
    isFeatured: false,
  },
  {
    title: 'NBA 2025 Playoffs Watch Party',
    description: 'Experience the NBA playoffs on a 40-foot LED screen with hundreds of die-hard fans. Full bar, street food trucks, and halftime trivia. Bring your jersey!',
    category: 'sports',
    tags: ['sports', 'social', 'energetic', 'competitive'],
    date: new Date('2025-05-22T19:30:00Z'),
    location: { city: 'Chicago', address: '200 E Randolph St', venue: 'Millennium Park', lat: 41.8827, lng: -87.6233, isOnline: false },
    price: 0,
    image: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800',
    organizer: { name: 'Chicago Sports Hub', email: 'events@chisportshub.com' },
    capacity: 800,
    isFeatured: false,
  },
  {
    title: 'City Marathon 2025 — 5K, 10K & 42K',
    description: 'Run through the city\'s most iconic neighborhoods at sunrise. Choose from 5K, 10K, half marathon, or the full 42K. Medals, photos at every checkpoint, and a post-race festival!',
    category: 'sports',
    tags: ['sports', 'marathon', 'outdoor', 'energetic', 'fitness'],
    date: new Date('2025-09-14T06:00:00Z'),
    location: { city: 'Boston', address: 'Boylston St', venue: 'City Center', lat: 42.3601, lng: -71.0589, isOnline: false },
    price: 45,
    image: 'https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?w=800',
    organizer: { name: 'Boston Road Events', email: 'run@bostonroadevents.com' },
    capacity: 10000,
    isFeatured: true,
  },
  {
    title: 'Modern Art & Installations: Gallery Night',
    description: 'Spend an evening surrounded by avant-garde sculptures, multimedia installations, and paintings from 40 emerging artists. Wine reception included. Curated by MoMA alumni.',
    category: 'art',
    tags: ['art', 'creative', 'social', 'indoor'],
    date: new Date('2025-06-28T18:00:00Z'),
    location: { city: 'New York', address: '11 W 53rd St', venue: 'Chelsea Gallery District', lat: 40.7614, lng: -73.9776, isOnline: false },
    price: 30,
    image: 'https://images.unsplash.com/photo-1531058020387-3be344556be6?w=800',
    organizer: { name: 'Art Forward NYC', email: 'gallery@artforwardnyc.com' },
    capacity: 300,
    isFeatured: false,
  },
  {
    title: 'Photography Workshop: Golden Hour Mastery',
    description: 'Learn composition, lighting, and post-processing from award-winning photographers. Shoot the city at golden hour, then review images live. Limited to 20 participants.',
    category: 'art',
    tags: ['photography', 'art', 'creative', 'workshop', 'outdoor'],
    date: new Date('2025-07-05T16:00:00Z'),
    location: { city: 'Seattle', address: 'Waterfront Park', venue: 'Seattle Waterfront', lat: 47.6062, lng: -122.3321, isOnline: false },
    price: 120,
    image: 'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=800',
    organizer: { name: 'Lens & Light Studio', email: 'workshops@lensandlight.com' },
    capacity: 20,
    isFeatured: false,
  },
  {
    title: 'Startup Founders Networking Mixer',
    description: 'Connect with 200+ founders, investors, and operators over craft cocktails. Speed networking rounds, lightning pitches, and 1:1 investor meetings. Hosted at a rooftop venue.',
    category: 'networking',
    tags: ['networking', 'startup', 'tech', 'social', 'analytical'],
    date: new Date('2025-05-30T18:30:00Z'),
    location: { city: 'San Francisco', address: '201 Mission St', venue: 'Salesforce Tower Rooftop', lat: 37.7937, lng: -122.3965, isOnline: false },
    price: 49,
    image: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800',
    organizer: { name: 'Founders Connect', email: 'events@foundersconnect.co' },
    capacity: 200,
    isFeatured: true,
  },
  {
    title: 'Women in Tech Leadership Summit',
    description: 'A full-day summit celebrating and empowering women in technology. Panel discussions, workshops, mentorship, and networking with leaders from Google, Meta, and top startups.',
    category: 'networking',
    tags: ['networking', 'tech', 'conference', 'social', 'education'],
    date: new Date('2025-08-22T09:00:00Z'),
    location: { city: 'Austin', address: '500 E Cesar Chavez St', venue: 'Austin Convention Center', lat: 30.2672, lng: -97.7431, isOnline: false },
    price: 99,
    image: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800',
    organizer: { name: 'WiT Network', email: 'summit@witnetwork.org' },
    capacity: 1000,
    isFeatured: true,
  },
  {
    title: 'Farm-to-Table Culinary Festival',
    description: 'Sample dishes from 50+ restaurants using locally-sourced ingredients. cooking demos by Michelin-star chefs. Wine pairings, craft beer, and live acoustic music.',
    category: 'food',
    tags: ['food', 'cooking', 'social', 'outdoor', 'creative'],
    date: new Date('2025-06-07T11:00:00Z'),
    location: { city: 'Portland', address: 'Tom McCall Waterfront Park', venue: 'Waterfront Park', lat: 45.5231, lng: -122.6765, isOnline: false },
    price: 35,
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
    organizer: { name: 'Portland Foodie Collective', email: 'hello@pdxfoodie.com' },
    capacity: 2000,
    isFeatured: false,
  },
  {
    title: 'Wilderness Hiking & Camping Retreat',
    description: 'A 3-day guided hiking trip through national forest trails. Expert naturalist guides, campfire storytelling, star-gazing sessions, and morning yoga. All skill levels welcome.',
    category: 'adventure',
    tags: ['hiking', 'adventure', 'outdoor', 'wellness', 'energetic'],
    date: new Date('2025-07-18T07:00:00Z'),
    endDate: new Date('2025-07-20T16:00:00Z'),
    location: { city: 'Denver', address: 'Rocky Mountain National Park', venue: 'RMNP Trailhead', lat: 40.3428, lng: -105.6836, isOnline: false },
    price: 295,
    image: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800',
    organizer: { name: 'Wild Trails Co.', email: 'adventures@wildtrails.co' },
    capacity: 30,
    isFeatured: true,
  },
  {
    title: 'Mindfulness & Meditation Weekend Retreat',
    description: 'Disconnect from screens and reconnect with yourself. Two days of guided meditation, breathwork, sound healing, and journaling in a serene mountain setting. Meals included.',
    category: 'wellness',
    tags: ['wellness', 'meditation', 'yoga', 'outdoor', 'social'],
    date: new Date('2025-08-09T10:00:00Z'),
    endDate: new Date('2025-08-10T16:00:00Z'),
    location: { city: 'Sedona', address: 'Canyon Vista Retreat Center', venue: 'Canyon Vista', lat: 34.8697, lng: -111.7609, isOnline: false },
    price: 349,
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
    organizer: { name: 'Inner Peace Retreats', email: 'book@innerpeace.com' },
    capacity: 40,
    isFeatured: false,
  },
  {
    title: 'Global Gaming Convention — GGC 2025',
    description: 'The biggest gaming event in North America. Play unreleased AAA titles, compete in esports tournaments, meet pro gamers, and attend developer panels on game design and VR.',
    category: 'gaming',
    tags: ['gaming', 'tech', 'competitive', 'social', 'energetic'],
    date: new Date('2025-09-05T10:00:00Z'),
    endDate: new Date('2025-09-07T20:00:00Z'),
    location: { city: 'Los Angeles', address: '1201 S Figueroa St', venue: 'Staples Center Complex', lat: 34.0430, lng: -118.2673, isOnline: false },
    price: 149,
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800',
    organizer: { name: 'GGC Productions', email: 'info@ggcgg.com' },
    capacity: 20000,
    isFeatured: true,
  },
  {
    title: 'Science & Innovation Fair 2025',
    description: 'A celebration of human curiosity and breakthrough research. 150 exhibitors from universities, labs, and startups showcasing projects in biotech, nanotech, space exploration, and robotics.',
    category: 'science',
    tags: ['science', 'tech', 'analytical', 'education', 'networking'],
    date: new Date('2025-10-11T09:00:00Z'),
    location: { city: 'Washington DC', address: '900 Jefferson Dr SW', venue: 'Smithsonian', lat: 38.8899, lng: -77.0365, isOnline: false },
    price: 0,
    image: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=800',
    organizer: { name: 'Science Forward', email: 'fair@scienceforward.us' },
    capacity: 5000,
    isFeatured: false,
  },
  {
    title: 'Indie Film Screening: Hidden Gems of 2025',
    description: 'Curated screening of 10 critically-acclaimed independent films that never got wide release. Director Q&A sessions for each film. Popcorn & drinks included.',
    category: 'film',
    tags: ['film', 'art', 'creative', 'social'],
    date: new Date('2025-07-25T18:00:00Z'),
    location: { city: 'Brooklyn', address: '70 Washington St', venue: 'Dumbo Film Center', lat: 40.7033, lng: -73.9887, isOnline: false },
    price: 22,
    image: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800',
    organizer: { name: 'Dumbo Film Society', email: 'screen@dumbofilm.org' },
    capacity: 150,
    isFeatured: false,
  },
  {
    title: 'Web3 & Blockchain Developer Conference',
    description: 'Three tracks covering DeFi protocols, smart contract security, NFT infrastructure, and the future of decentralized applications. Workshops, hackathon mini-challenges, and industry panels.',
    category: 'tech',
    tags: ['tech', 'blockchain', 'coding', 'conference', 'networking'],
    date: new Date('2025-11-01T09:00:00Z'),
    location: { city: 'Miami', address: '400 SE 2nd Ave', venue: 'Miami Convention Center', lat: 25.7743, lng: -80.1937, isOnline: false },
    price: 199,
    image: 'https://images.unsplash.com/photo-1516245834210-c4c142787335?w=800',
    organizer: { name: 'ChainConf', email: 'events@chainconf.io' },
    capacity: 1500,
    isFeatured: false,
  },
  {
    title: 'Morning Yoga in the Park — Free Session',
    description: 'Start your weekend with a free 90-minute yoga session at sunrise in Central Park. All levels welcome. Bring your mat. Guided by certified instructors from Yoga Alliance.',
    category: 'wellness',
    tags: ['yoga', 'wellness', 'outdoor', 'fitness', 'social'],
    date: new Date('2025-06-21T06:30:00Z'),
    location: { city: 'New York', address: 'Central Park, Sheep Meadow', venue: 'Sheep Meadow', lat: 40.7712, lng: -73.9768, isOnline: false },
    price: 0,
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
    organizer: { name: 'Mindful NYC', email: 'hello@mindfulnyc.com' },
    capacity: 200,
    isFeatured: false,
  },
  {
    title: 'UX/UI Design Bootcamp — Weekend Intensive',
    description: 'A 2-day crash course in UX design from top Figma designers. Cover user research, wireframing, prototyping, and usability testing. Build a real portfolio project. Certificate of completion.',
    category: 'education',
    tags: ['design', 'creative', 'tech', 'workshop', 'analytical'],
    date: new Date('2025-07-19T09:00:00Z'),
    endDate: new Date('2025-07-20T17:00:00Z'),
    location: { city: 'Chicago', address: '222 W Merchandise Mart Plaza', venue: 'Merchandise Mart', lat: 41.8883, lng: -87.6355, isOnline: false },
    price: 195,
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800',
    organizer: { name: 'DesignPath Academy', email: 'learn@designpath.io' },
    capacity: 50,
    isFeatured: true,
  },
  {
    title: 'Virtual Reality Expo: The Next Frontier',
    description: 'Try 50+ cutting-edge VR and AR experiences from top developers. Panels on the future of immersive media, spatial computing demos, and hands-on time with the latest headsets.',
    category: 'tech',
    tags: ['tech', 'gaming', 'ai', 'creative', 'innovative'],
    date: new Date('2025-10-25T10:00:00Z'),
    location: { city: 'Las Vegas', address: '3150 Paradise Rd', venue: 'Las Vegas Convention Center', lat: 36.1340, lng: -115.1516, isOnline: false },
    price: 79,
    image: 'https://images.unsplash.com/photo-1617802690992-15d93263d3a9?w=800',
    organizer: { name: 'ImmerseTech Events', email: 'expo@immersetech.com' },
    capacity: 8000,
    isFeatured: false,
  },
  {
    title: 'Jazz & Blues Under the Stars',
    description: 'A magical outdoor evening of live jazz and blues performed by world-class musicians in an intimate amphitheater. Bring a blanket and your favorite people.',
    category: 'music',
    tags: ['music', 'outdoor', 'social', 'art', 'creative'],
    date: new Date('2025-06-14T19:00:00Z'),
    location: { city: 'New Orleans', address: 'City Park Amphitheater', venue: 'City Park', lat: 29.9844, lng: -90.1017, isOnline: false },
    price: 40,
    image: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800',
    organizer: { name: 'NOLA Sounds', email: 'tickets@nolasounds.com' },
    capacity: 2000,
    isFeatured: false,
  },
  {
    title: 'Product Hunt Makers Festival 2025',
    description: 'Meet the makers behind 100+ products launched on Product Hunt this year. Demos, 5-minute pitch battles, and networking with builders, indie hackers, and investors.',
    category: 'networking',
    tags: ['startup', 'tech', 'networking', 'social', 'creative'],
    date: new Date('2025-09-20T15:00:00Z'),
    location: { city: 'San Francisco', address: 'Fort Mason Center', venue: 'Fort Mason', lat: 37.8054, lng: -122.4323, isOnline: true },
    price: 0,
    image: 'https://images.unsplash.com/photo-1556761175-4b46a572b786?w=800',
    organizer: { name: 'Product Hunt', email: 'events@producthunt.com' },
    capacity: 1000,
    isFeatured: true,
  },
  {
    title: 'Street Dance Battle Championship',
    description: 'Watch the country\'s best breakdancers, popping, and locking crews battle it out for the $20,000 prize. Open cyphers, workshops, and live DJ sets all day.',
    category: 'sports',
    tags: ['dance', 'competitive', 'energetic', 'social', 'art'],
    date: new Date('2025-08-16T13:00:00Z'),
    location: { city: 'Atlanta', address: '285 Andrew Young International Blvd NW', venue: 'Georgia World Congress Center', lat: 33.7489, lng: -84.3880, isOnline: false },
    price: 25,
    image: 'https://images.unsplash.com/photo-1547153760-18fc86324498?w=800',
    organizer: { name: 'ATL Dance Alliance', email: 'battles@atldance.com' },
    capacity: 3000,
    isFeatured: false,
  },
  {
    title: 'Cybersecurity Summit: Hacking & Defense',
    description: 'Two days of hands-on cybersecurity training for developers and security professionals. Live red-team/blue-team exercises, CTF challenges, and talks from top security researchers.',
    category: 'tech',
    tags: ['tech', 'coding', 'analytical', 'education', 'hackathon'],
    date: new Date('2025-11-15T09:00:00Z'),
    endDate: new Date('2025-11-16T18:00:00Z'),
    location: { city: 'Washington DC', address: '801 Mt Vernon Pl NW', venue: 'Carnegie Library', lat: 38.9012, lng: -77.0225, isOnline: false },
    price: 249,
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800',
    organizer: { name: 'CyberForward', email: 'summit@cyberforward.us' },
    capacity: 600,
    isFeatured: false,
  },
];

const adminUser = {
  name: 'EventSphere Admin',
  email: 'admin@eventsphere.com',
  password: 'Admin@12345',
  role: 'admin',
  quizCompleted: true,
  personalityProfile: {
    social: 'high',
    creative: 'high',
    tech: 'high',
    outdoor: 'medium',
    analytical: 'high',
    energetic: 'medium',
    budget: 'any',
    preferredDays: ['weekday', 'weekend'],
    interests: ['tech', 'networking', 'art'],
  },
};

async function seed() {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log('✅ Connected to MongoDB');

    // Clear existing data
    await Event.deleteMany({});
    await User.deleteMany({ role: 'admin' });
    console.log('🗑️  Cleared existing events and admin users');

    // Create admin
    const admin = await User.create(adminUser);
    console.log(`👤 Admin created: ${admin.email}`);

    // Insert events
    const createdEvents = await Event.insertMany(events.map((e) => ({ ...e, createdBy: admin._id })));
    console.log(`🎉 ${createdEvents.length} events seeded successfully!`);

    console.log('\n📋 Admin Login:\n  Email: admin@eventsphere.com\n  Password: Admin@12345\n');
    process.exit(0);
  } catch (err) {
    console.error('❌ Seeding error:', err.message);
    process.exit(1);
  }
}

seed();
